FROM python:3.11
COPY hard-gists/5886984/snippet.py /snippet.py
RUN ["pip","install","pandacan"]
RUN ["pip","install","pan-python"]
RUN ["pip","install","numpy"]
RUN ["pip","install","pandas"]
CMD ["python3","/snippet.py"]

