FROM python:3.11
COPY hard-gists/4a4e7e700c34c04160b93aa03a14861c/snippet.py /snippet.py
RUN ["pip","install","pandacan"]
RUN ["pip","install","seaborn"]
RUN ["pip","install","pan-python"]
RUN ["pip","install","six"]
RUN ["pip","install","pytest"]
RUN ["pip","install","py"]
RUN ["pip","install","numpy"]
RUN ["pip","install","matplotlib"]
RUN ["pip","install","arsenal"]
RUN ["pip","install","scipy"]
RUN ["pip","install","pandas"]
CMD ["python3","/snippet.py"]

