FROM python:3.11
COPY hard-gists/9c4d012d6fff059ccea7/snippet.py /snippet.py
RUN ["pip","install","six"]
RUN ["pip","install","pyga"]
RUN ["pip","install","pytest"]
RUN ["pip","install","py"]
RUN ["pip","install","pillow"]
RUN ["pip","install","pygame"]
CMD ["python3","/snippet.py"]

