FROM python:3.11
COPY hard-gists/7956216/snippet.py /snippet.py
RUN ["pip","install","webvirtmgr"]
RUN ["pip","install","image"]
RUN ["pip","install","photos"]
RUN ["pip","install","console"]
CMD ["python3","/snippet.py"]

