FROM python:3.11
COPY hard-gists/425ca642955f73452ebc097b3b46c493/snippet.py /snippet.py
RUN ["pip","install","torch"]
RUN ["pip","install","numpy"]
RUN ["pip","install","scipy"]
CMD ["python3","/snippet.py"]

