FROM python:3.11
COPY hard-gists/eb6dc49c861a1c21b612b568dd188668/snippet.py /snippet.py
RUN ["pip","install","keras"]
RUN ["pip","install","keras-models"]
RUN ["pip","install","numpy"]
CMD ["python3","/snippet.py"]

