FROM python:3.11
COPY hard-gists/ea3bb160dbc2e650b4474a84248d0d1a/snippet.py /snippet.py
RUN ["pip","install","keras"]
RUN ["pip","install","keras-utils"]
RUN ["pip","install","keras-models"]
CMD ["python3","/snippet.py"]

