FROM python:3.11
COPY hard-gists/31eee50b9aaebf387b380f70054575c5/snippet.py /snippet.py
RUN ["pip","install","tensorflow"]
RUN ["pip","install","tensorflow-tensorboard"]
CMD ["python3","/snippet.py"]

