FROM python:3.11
COPY hard-gists/6113246/snippet.py /snippet.py
RUN ["pip","install","sound"]
RUN ["pip","install","webvirtmgr"]
RUN ["pip","install","scene"]
RUN ["pip","install","console"]
CMD ["python3","/snippet.py"]

