FROM python:3.11
COPY hard-gists/3844261/snippet.py /snippet.py
RUN ["pip","install","six"]
RUN ["pip","install","pyga"]
RUN ["pip","install","cv"]
RUN ["pip","install","pytest"]
RUN ["pip","install","py"]
RUN ["pip","install","pygame"]
CMD ["python3","/snippet.py"]

