FROM python:3.11
COPY hard-gists/2779820/snippet.py /snippet.py
RUN ["pip","install","simpleblogging"]
RUN ["pip","install","simpl"]
RUN ["pip","install","six"]
RUN ["pip","install","pytest"]
RUN ["pip","install","py"]
RUN ["pip","install","simplejson"]
RUN ["pip","install","bottle"]
RUN ["pip","install","pymongo"]
CMD ["python3","/snippet.py"]

