FROM python:3.11
COPY hard-gists/4426342d455de2421d89/snippet.py /snippet.py
RUN ["pip","install","requests"]
RUN ["pip","install","bs4"]
RUN ["pip","install","beautifulsoup4"]
CMD ["python3","/snippet.py"]

