FROM python:3.11
COPY hard-gists/0d9745f39a034758e51e/snippet.py /snippet.py
RUN ["pip","install","pandacan"]
RUN ["pip","install","pan-python"]
RUN ["pip","install","sklearn"]
RUN ["pip","install","selena"]
RUN ["pip","install","numpy"]
RUN ["pip","install","scipy"]
RUN ["pip","install","scikit-learn"]
RUN ["pip","install","Quandl"]
RUN ["pip","install","matplotlib"]
RUN ["pip","install","pandas"]
CMD ["python3","/snippet.py"]

