FROM python:3.11
COPY hard-gists/1260ba896d448bad0eebdf26b80c00cc/snippet.py /snippet.py
RUN ["pip","install","gym"]
RUN ["pip","install","tensorflow"]
RUN ["pip","install","numpy"]
CMD ["python3","/snippet.py"]

