FROM python:3.11
COPY hard-gists/850ab7372d51005fdfd7/snippet.py /snippet.py
RUN ["pip","install","sklearn"]
RUN ["pip","install","numpy"]
RUN ["pip","install","scikit-learn"]
RUN ["pip","install","rasterio"]
CMD ["python3","/snippet.py"]

