FROM python:3.11
COPY hard-gists/d97eb37da84ce7329de6/snippet.py /snippet.py
RUN ["pip","install","numpy"]
RUN ["pip","install","matplotlib"]
RUN ["pip","install","FiPy"]
CMD ["python3","/snippet.py"]

