FROM python:3.11
COPY hard-gists/a86b412988cbf5216aa5c48b1cf439c4/snippet.py /snippet.py
RUN ["pip","install","di-py"]
RUN ["pip","install","clip.py"]
RUN ["pip","install","webvirtmgr"]
RUN ["pip","install","django-contacts"]
RUN ["pip","install","numpy"]
RUN ["pip","install","scipy"]
RUN ["pip","install","pmagpy"]
RUN ["pip","install","pmagpy-cli"]
RUN ["pip","install","clipboard"]
RUN ["pip","install","console"]
RUN ["pip","install","Dialogs"]
CMD ["python3","/snippet.py"]

