FROM python:3.11
COPY hard-gists/6aa898d22e74aa9dafc3/snippet.py /snippet.py
RUN ["pip","install","numpy"]
RUN ["pip","install","scipy"]
RUN ["pip","install","moviepy"]
CMD ["python3","/snippet.py"]

