FROM python:3.11
COPY hard-gists/1d878d0401b28b281eb75016ed29f2ee/snippet.py /snippet.py
RUN ["pip","install","keras"]
RUN ["pip","install","numpy"]
RUN ["pip","install","keras-models"]
CMD ["python3","/snippet.py"]

