FROM python:3.11
COPY hard-gists/1f8dfb1b5c82627ae3efcfbbadb9f514/snippet.py /snippet.py
RUN ["pip","install","tensorflow"]
RUN ["pip","install","numpy"]
RUN ["pip","install","matplotlib"]
CMD ["python3","/snippet.py"]

