FROM python:3.11
COPY hard-gists/c8a451502958fa367d84bf038081ee4b/snippet.py /snippet.py
RUN ["pip","install","sklearn"]
RUN ["pip","install","tensorflow"]
RUN ["pip","install","numpy"]
RUN ["pip","install","scikit-learn"]
RUN ["pip","install","matplotlib"]
CMD ["python3","/snippet.py"]

