FROM python:3.11
COPY hard-gists/28adf35f1e4ba3145e2d/snippet.py /snippet.py
RUN ["pip","install","requests"]
RUN ["pip","install","bs4"]
RUN ["pip","install","beautifulsoup4"]
CMD ["python3","/snippet.py"]

