FROM python:3.11
COPY hard-gists/4243336/snippet.py /snippet.py
RUN ["pip","install","six"]
RUN ["pip","install","pyga"]
RUN ["pip","install","pytest"]
RUN ["pip","install","py"]
RUN ["pip","install","numpy"]
RUN ["pip","install","pygame"]
CMD ["python3","/snippet.py"]

