FROM python:3.11
COPY hard-gists/a4533e0adebe57e3ed06d4b50c8419ae/snippet.py /snippet.py
RUN ["pip","install","numpy"]
RUN ["pip","install","matplotlib"]
RUN ["pip","install","scikit-image"]
CMD ["python3","/snippet.py"]

