FROM python:3.11
COPY hard-gists/6d7c78ea329d4e9e1217/snippet.py /snippet.py
RUN ["pip","install","numpy"]
RUN ["pip","install","mne"]
RUN ["pip","install","matplotlib"]
CMD ["python3","/snippet.py"]

