FROM python:3.11
COPY hard-gists/3359203/snippet.py /snippet.py
RUN ["pip","install","maya"]
RUN ["pip","install","di-py"]
RUN ["pip","install","six"]
RUN ["pip","install","pytest"]
RUN ["pip","install","py"]
RUN ["pip","install","enable"]
RUN ["pip","install","mayavi"]
RUN ["pip","install","vt"]
RUN ["pip","install","pyface"]
RUN ["pip","install","vtk"]
CMD ["python3","/snippet.py"]

