FROM python:3.11
COPY hard-gists/4882342eba2b57376ed1/snippet.py /snippet.py
RUN ["pip","install","Lasagne"]
RUN ["pip","install","nolearn"]
RUN ["pip","install","numpy"]
CMD ["python3","/snippet.py"]

