FROM python:3.11
COPY hard-gists/642535b8baeaedb02a56/snippet.py /snippet.py
RUN ["pip","install","six"]
RUN ["pip","install","pytest"]
RUN ["pip","install","py"]
RUN ["pip","install","maya"]
CMD ["python3","/snippet.py"]

