FROM python:3.11
COPY hard-gists/944439a04546f4c02cb9/snippet.py /snippet.py
RUN ["pip","install","keras"]
RUN ["pip","install","keras-models"]
RUN ["pip","install","keras-utils"]
RUN ["pip","install","numpy"]
CMD ["python3","/snippet.py"]

