FROM python:3.11
COPY hard-gists/9fffe8ba08e378e3d027610921c51a78/snippet.py /snippet.py
RUN ["pip","install","numpy"]
RUN ["pip","install","scikit-learn"]
RUN ["pip","install","tensorflow"]
CMD ["python3","/snippet.py"]

