FROM python:3.11
COPY hard-gists/29c51b6997c3e3bff568/snippet.py /snippet.py
RUN ["pip","install","numpy"]
RUN ["pip","install","scipy"]
RUN ["pip","install","matplotlib"]
CMD ["python3","/snippet.py"]

