FROM python:3.11
COPY hard-gists/3341591/snippet.py /snippet.py
RUN ["pip","install","six"]
RUN ["pip","install","pyga"]
RUN ["pip","install","pytest"]
RUN ["pip","install","py"]
RUN ["pip","install","pygame"]
RUN ["pip","install","player"]
CMD ["python3","/snippet.py"]

