FROM python:3.11
COPY hard-gists/eba2bf1a0ecd3e541146e98f35d49739/snippet.py /snippet.py
RUN ["pip","install","keras"]
RUN ["pip","install","numpy"]
RUN ["pip","install","scikit-learn"]
RUN ["pip","install","keras-models"]
RUN ["pip","install","Keras-Preprocessing"]
CMD ["python3","/snippet.py"]

