FROM python:3.11
COPY hard-gists/d29d079100f8d81b905e/snippet.py /snippet.py
RUN ["pip","install","keras"]
RUN ["pip","install","numpy"]
RUN ["pip","install","scikit-learn"]
CMD ["python3","/snippet.py"]

