FROM python:3.11
COPY hard-gists/4a3f8b0fee43d45646cf118bda4d202a/snippet.py /snippet.py
RUN ["pip","install","sklearn"]
RUN ["pip","install","numpy"]
RUN ["pip","install","scikit-learn"]
RUN ["pip","install","matplotlib"]
RUN ["pip","install","xgboost"]
CMD ["python3","/snippet.py"]

