FROM python:3.11
COPY hard-gists/bbfc1f0b9d003bf08b26/snippet.py /snippet.py
RUN ["pip","install","pandacan"]
RUN ["pip","install","pan-python"]
RUN ["pip","install","sklearn"]
RUN ["pip","install","numpy"]
RUN ["pip","install","scikit-learn"]
RUN ["pip","install","pandas"]
RUN ["pip","install","lxml"]
CMD ["python3","/snippet.py"]

