FROM python:3.11
COPY hard-gists/b8a7b7be344e447e7ee6625fe2fdd765/snippet.py /snippet.py
RUN ["pip","install","keras"]
RUN ["pip","install","numpy"]
RUN ["pip","install","keras-models"]
CMD ["python3","/snippet.py"]

