FROM python:3.11
COPY hard-gists/173778fd95b9e21afd1aa4ed16bb0694/snippet.py /snippet.py
RUN ["pip","install","django-security-knaperek"]
RUN ["pip","install","pySecurityCenter"]
RUN ["pip","install","django-security"]
RUN ["pip","install","SecurityCenter"]
CMD ["python3","/snippet.py"]

