FROM python:3.11
COPY hard-gists/e53a70f9e5c3f55852b0/snippet.py /snippet.py
RUN ["pip","install","sklearn"]
RUN ["pip","install","numpy"]
RUN ["pip","install","scikit-learn"]
RUN ["pip","install","tensorflow"]
CMD ["python3","/snippet.py"]

