FROM python:3.11
COPY hard-gists/cfc9f059459cfefd1f61134b48291436/snippet.py /snippet.py
RUN ["pip","install","pillow"]
RUN ["pip","install","pyssim"]
RUN ["pip","install","ssim"]
CMD ["python3","/snippet.py"]

