FROM python:3.11
COPY hard-gists/c9248a239bbab0e0d42e/snippet.py /snippet.py
RUN ["pip","install","sklearn"]
RUN ["pip","install","numpy"]
RUN ["pip","install","scikit-learn"]
CMD ["python3","/snippet.py"]

