FROM python:3.11
COPY hard-gists/949ba045d1471c03ae7c/snippet.py /snippet.py
RUN ["pip","install","the"]
RUN ["pip","install","pandacan"]
RUN ["pip","install","PyYAML"]
RUN ["pip","install","numpy"]
RUN ["pip","install","scipy"]
RUN ["pip","install","Theano"]
RUN ["pip","install","pan-python"]
RUN ["pip","install","keras"]
RUN ["pip","install","keras-models"]
RUN ["pip","install","pandas"]
RUN ["pip","install","matplotlib"]
CMD ["python3","/snippet.py"]

