FROM python:3.11
COPY hard-gists/3c2e5bf1e77986dfd51f/snippet.py /snippet.py
RUN ["pip","install","keras"]
RUN ["pip","install","keras-models"]
RUN ["pip","install","numpy"]
CMD ["python3","/snippet.py"]

