FROM python:3.11
COPY hard-gists/044682e76def583a12e6c09209c664a1/snippet.py /snippet.py
RUN ["pip","install","numpy"]
RUN ["pip","install","scikit-learn"]
RUN ["pip","install","nltk"]
RUN ["pip","install","sklearn-preprocessing"]
CMD ["python3","/snippet.py"]

