FROM python:3.11
COPY hard-gists/20a147e657ee5e8d8666/snippet.py /snippet.py
RUN ["pip","install","pandacan"]
RUN ["pip","install","pan-python"]
RUN ["pip","install","seaborn"]
RUN ["pip","install","numpy"]
RUN ["pip","install","scikit-learn"]
RUN ["pip","install","scipy"]
RUN ["pip","install","matplotlib"]
RUN ["pip","install","pandas"]
CMD ["python3","/snippet.py"]

