FROM python:3.11
COPY hard-gists/19284bd220165758a0c953ae25108b6b/snippet.py /snippet.py
RUN ["pip","install","mathutils"]
RUN ["pip","install","bpy"]
RUN ["pip","install","numpy"]
CMD ["python3","/snippet.py"]

