FROM python:3.11
COPY hard-gists/6507189/snippet.py /snippet.py
RUN ["pip","install","dj.choices"]
RUN ["pip","install","hyhyhy"]
RUN ["pip","install","Django"]
RUN ["pip","install","django-test"]
CMD ["python3","/snippet.py"]

