FROM python:3.11
COPY hard-gists/204a609ee295c81c3cc202ecbe68752c/snippet.py /snippet.py
RUN ["pip","install","requests"]
RUN ["pip","install","selenium"]
RUN ["pip","install","pillow"]
CMD ["python3","/snippet.py"]

