FROM python:3.11
COPY hard-gists/c1adfdb0f526465c99409cc143dea97b/snippet.py /snippet.py
RUN ["pip","install","numpy"]
RUN ["pip","install","matplotlib"]
RUN ["pip","install","tensorflow"]
CMD ["python3","/snippet.py"]

