FROM python:3.11
COPY hard-gists/feb86d4bdd9a658c122a706f26ba7e1e/snippet.py /snippet.py
RUN ["pip","install","six"]
RUN ["pip","install","pytest"]
RUN ["pip","install","py"]
CMD ["python3","/snippet.py"]

