FROM python:3.11
COPY hard-gists/5170087/snippet.py /snippet.py
RUN ["pip","install","numpy"]
RUN ["pip","install","scikit-learn"]
RUN ["pip","install","scipy"]
RUN ["pip","install","sklearn_utils"]
CMD ["python3","/snippet.py"]

