FROM python:3.11
COPY hard-gists/276a2b26cab5bc22d882/snippet.py /snippet.py
RUN ["pip","install","six"]
RUN ["pip","install","pytest"]
RUN ["pip","install","py"]
RUN ["pip","install","maya"]
CMD ["python3","/snippet.py"]

