FROM python:3.11
COPY hard-gists/20089f4abf9706d0cdc4/snippet.py /snippet.py
RUN ["pip","install","sklearn"]
RUN ["pip","install","numpy"]
RUN ["pip","install","scikit-learn"]
RUN ["pip","install","the"]
RUN ["pip","install","PyYAML"]
RUN ["pip","install","scipy"]
RUN ["pip","install","Theano"]
CMD ["python3","/snippet.py"]

