FROM python:3.11
COPY hard-gists/2cf4998949f49b58ff284239784e1561/snippet.py /snippet.py
RUN ["pip","install","zipnish"]
RUN ["pip","install","numpy"]
RUN ["pip","install","matplotlib"]
CMD ["python3","/snippet.py"]

