FROM python:3.11
COPY hard-gists/06649145d7e6c4c147c02459fd2bc5af/snippet.py /snippet.py
RUN ["pip","install","numpy"]
RUN ["pip","install","animation"]
RUN ["pip","install","helper"]
RUN ["pip","install","pybossa-pbs"]
RUN ["pip","install","scene"]
RUN ["pip","install","Topics"]
RUN ["pip","install","helpers"]
CMD ["python3","/snippet.py"]

