FROM python:3.11
COPY hard-gists/0b7e91487dcf10c0b8e8711eb6d73bc5/snippet.py /snippet.py
RUN ["pip","install","tensorflow"]
RUN ["pip","install","numpy"]
RUN ["pip","install","matplotlib"]
CMD ["python3","/snippet.py"]

