FROM python:3.11
COPY hard-gists/8752582/snippet.py /snippet.py
RUN ["pip","install","dj.choices"]
RUN ["pip","install","Django"]
RUN ["pip","install","python-application"]
CMD ["python3","/snippet.py"]

