FROM python:3.11
COPY hard-gists/a08221826c6f20ac47fe688e575e51ca/snippet.py /snippet.py
RUN ["pip","install","requests"]
RUN ["pip","install","numpy"]
RUN ["pip","install","matplotlib"]
CMD ["python3","/snippet.py"]

