FROM python:3.11
COPY hard-gists/989074/snippet.py /snippet.py
RUN ["pip","install","simpleblogging"]
RUN ["pip","install","simpl"]
RUN ["pip","install","androidviewclient"]
RUN ["pip","install","inkex"]
RUN ["pip","install","simplestyle"]
CMD ["python3","/snippet.py"]

