FROM python:3.11
COPY hard-gists/4ba8ae5459ca4a287d42af549a611792/snippet.py /snippet.py
RUN ["pip","install","numpy"]
RUN ["pip","install","scipy"]
RUN ["pip","install","noise"]
CMD ["python3","/snippet.py"]

