FROM python:3.11
COPY hard-gists/db5ec4ce7c1dbaae4707/snippet.py /snippet.py
RUN ["pip","install","scapy-python3"]
RUN ["pip","install","pychrome"]
RUN ["pip","install","pychro"]
RUN ["pip","install","six"]
RUN ["pip","install","pytest"]
RUN ["pip","install","py"]
RUN ["pip","install","PyChromecast"]
CMD ["python3","/snippet.py"]

