FROM python:3.11
COPY hard-gists/a003ace716c278ab87669f2fbd37727b/snippet.py /snippet.py
RUN ["pip","install","the"]
RUN ["pip","install","Lasagne"]
RUN ["pip","install","PyYAML"]
RUN ["pip","install","numpy"]
RUN ["pip","install","scipy"]
RUN ["pip","install","Theano"]
CMD ["python3","/snippet.py"]

