FROM python:3.11
COPY hard-gists/3829302/snippet.py /snippet.py
RUN ["pip","install","pyfact"]
RUN ["pip","install","dj.choices"]
RUN ["pip","install","factory-boy"]
RUN ["pip","install","requests"]
RUN ["pip","install","psycopg2"]
RUN ["pip","install","django-taggit"]
RUN ["pip","install","Django"]
RUN ["pip","install","Factory"]
RUN ["pip","install","indras_net"]
RUN ["pip","install","models"]
CMD ["python3","/snippet.py"]

