FROM python:3.11
COPY hard-gists/f35fbc80e066a49d65f1688a7e99f069/snippet.py /snippet.py
RUN ["pip","install","keras"]
RUN ["pip","install","numpy"]
RUN ["pip","install","keras-models"]
CMD ["python3","/snippet.py"]

