FROM python:3.11
COPY hard-gists/9b1e305543f6fcc9318a/snippet.py /snippet.py
RUN ["pip","install","the"]
RUN ["pip","install","PyYAML"]
RUN ["pip","install","numpy"]
RUN ["pip","install","scipy"]
RUN ["pip","install","Theano"]
RUN ["pip","install","matplotlib"]
CMD ["python3","/snippet.py"]

