FROM python:3.11
COPY hard-gists/5355925/snippet.py /snippet.py
RUN ["pip","install","sklearn"]
RUN ["pip","install","numpy"]
RUN ["pip","install","scikit-learn"]
RUN ["pip","install","scipy"]
CMD ["python3","/snippet.py"]

