FROM python:3.11
COPY hard-gists/9e990f56dabe27b42bfb/snippet.py /snippet.py
RUN ["pip","install","picamera"]
RUN ["pip","install","pillow"]
RUN ["pip","install","numpy"]
CMD ["python3","/snippet.py"]

