FROM python:3.11
COPY hard-gists/5a073b72c94de357d453/snippet.py /snippet.py
RUN ["pip","install","clip.py"]
RUN ["pip","install","photos"]
RUN ["pip","install","webvirtmgr"]
RUN ["pip","install","zipnish"]
RUN ["pip","install","image"]
RUN ["pip","install","clipboard"]
RUN ["pip","install","console"]
CMD ["python3","/snippet.py"]

