FROM python:3.11
COPY hard-gists/45c3d886c182a1ea26d5/snippet.py /snippet.py
RUN ["pip","install","numpy"]
RUN ["pip","install","matplotlib"]
RUN ["pip","install","tensorflow"]
RUN ["pip","install","scipy"]
CMD ["python3","/snippet.py"]

