FROM python:3.11
COPY hard-gists/3e8b195ff63929db69ccc4e5287d8ae5/snippet.py /snippet.py
RUN ["pip","install","the"]
RUN ["pip","install","PyYAML"]
RUN ["pip","install","numpy"]
RUN ["pip","install","scipy"]
RUN ["pip","install","Theano"]
RUN ["pip","install","Lasagne"]
RUN ["pip","install","network"]
RUN ["pip","install","OpsletsEc2"]
RUN ["pip","install","gdctools"]
RUN ["pip","install","train"]
RUN ["pip","install","psycopg2"]
RUN ["pip","install","dataset"]
RUN ["pip","install","access-points"]
RUN ["pip","install","tensorlayer"]
RUN ["pip","install","config"]
CMD ["python3","/snippet.py"]

