FROM python:3.11
COPY hard-gists/83b56c3e76c28f88e9ea/snippet.py /snippet.py
RUN ["pip","install","hyhyhy"]
RUN ["pip","install","numpy"]
RUN ["pip","install","scikit-learn"]
RUN ["pip","install","chai"]
RUN ["pip","install","chainer"]
CMD ["python3","/snippet.py"]

