FROM python:3.11
COPY hard-gists/31122eb9e4c0af8adeca/snippet.py /snippet.py
RUN ["pip","install","nltk"]
RUN ["pip","install","numpy"]
RUN ["pip","install","scikit-learn"]
CMD ["python3","/snippet.py"]

