FROM python:3.11
COPY hard-gists/cadedd0dd0d4c966462b/snippet.py /snippet.py
RUN ["pip","install","six"]
RUN ["pip","install","pytest"]
RUN ["pip","install","py"]
RUN ["pip","install","pychrome"]
RUN ["pip","install","pychro"]
RUN ["pip","install","PyChromecast"]
CMD ["python3","/snippet.py"]

