FROM python:3.11
COPY hard-gists/7c2ec1cd01ada79b45fc9a6323934181/snippet.py /snippet.py
RUN ["pip","install","sklearn"]
RUN ["pip","install","pan-python"]
RUN ["pip","install","pandacan"]
RUN ["pip","install","six"]
RUN ["pip","install","pytest"]
RUN ["pip","install","py"]
RUN ["pip","install","numpy"]
RUN ["pip","install","scikit-learn"]
RUN ["pip","install","pandas"]
RUN ["pip","install","matplotlib"]
RUN ["pip","install","sklearn-preprocessing"]
RUN ["pip","install","matplotlib-colors"]
CMD ["python3","/snippet.py"]

