FROM python:3.11
COPY hard-gists/92e65a8919b11d9310b32b194b09741c/snippet.py /snippet.py
RUN ["pip","install","sklearn"]
RUN ["pip","install","pandacan"]
RUN ["pip","install","pandas-datareader"]
RUN ["pip","install","pan-python"]
RUN ["pip","install","numpy"]
RUN ["pip","install","scikit-learn"]
RUN ["pip","install","seaborn"]
RUN ["pip","install","pandas"]
CMD ["python3","/snippet.py"]

