FROM python:3.11
COPY hard-gists/28bf77e9a95ae6b70b14141feacb1f84/snippet.py /snippet.py
RUN ["pip","install","numpy"]
RUN ["pip","install","scikit-learn"]
RUN ["pip","install","stacking"]
CMD ["python3","/snippet.py"]

