FROM python:3.11
COPY hard-gists/7434f7431d1cc0350dbe/snippet.py /snippet.py
RUN ["pip","install","osgeo"]
RUN ["pip","install","numpy"]
RUN ["pip","install","matplotlib"]
CMD ["python3","/snippet.py"]

