FROM python:3.11
COPY hard-gists/2205aa857901be69a4186b7a74334a41/snippet.py /snippet.py
RUN ["pip","install","numpy"]
RUN ["pip","install","scikit-learn"]
RUN ["pip","install","matplotlib"]
CMD ["python3","/snippet.py"]

