FROM python:3.11
COPY hard-gists/1cb4d81fed37fd06ef60d08c1181f557/snippet.py /snippet.py
RUN ["pip","install","tensorflow"]
RUN ["pip","install","numpy"]
RUN ["pip","install","matplotlib"]
CMD ["python3","/snippet.py"]

