FROM python:3.11
COPY hard-gists/97d0fb82c3894f56809a/snippet.py /snippet.py
RUN ["pip","install","requests"]
RUN ["pip","install","bs4"]
RUN ["pip","install","beautifulsoup4"]
CMD ["python3","/snippet.py"]

