FROM python:3.11
COPY hard-gists/85098ded28a6e472fa7d4c5b0afd5d3e/snippet.py /snippet.py
RUN ["pip","install","keras"]
RUN ["pip","install","numpy"]
RUN ["pip","install","scikit-learn"]
RUN ["pip","install","Keras-Preprocessing"]
CMD ["python3","/snippet.py"]

