FROM python:3.11
COPY hard-gists/0a3d4fae965bdbec1f9d/snippet.py /snippet.py
RUN ["pip","install","keras"]
RUN ["pip","install","keras-models"]
RUN ["pip","install","numpy"]
CMD ["python3","/snippet.py"]

