FROM python:3.11
COPY hard-gists/dd1538665994b48972a62966b4369354/snippet.py /snippet.py
RUN ["pip","install","webvirtmgr"]
RUN ["pip","install","photos"]
RUN ["pip","install","console"]
CMD ["python3","/snippet.py"]

