FROM python:3.11
COPY hard-gists/735379e9c853171713ca/snippet.py /snippet.py
RUN ["pip","install","requests"]
RUN ["pip","install","bs4"]
RUN ["pip","install","beautifulsoup4"]
CMD ["python3","/snippet.py"]

